// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyClipboard(arg1) {
  return window['go']['main']['App']['CopyClipboard'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}
